language: node_js
node_js:
  - 'stable'
  - node
  - lts/*
cache:
  directories:
    - '~/.npm'
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_2c6bf604352c_key -iv $encrypted_2c6bf604352c_iv -in serviceAccount.json.enc -out serviceAccount.json -d
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli
script:
  - npm ci
  - npm run test:parallel
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
