const counties = [
  {
    id: 0,
    county: {
      name: '«Select county»',
      municipalities: undefined,
    },
  },
  {
    id: 1,
    county: {
      name: 'Ahvenanmaa',
      municipalities: [
        'Brändö',
        'Eckerö',
        'Finström',
        'Föglö',
        'Geta',
        'Hammarland',
        'Jomala',
        'Kumlinge',
        'Kökar',
        'Kumlinge',
        'Lemland',
        'Kumlinge',
        'Lumparland',
        'Maarianhamina',
        'Saltvik',
        'Sottunga',
        'Sund',
        'Vårdö',
      ],
    },
  },
  {
    id: 2,
    county: {
      name: 'Etelä-Karjala',
      municipalities: [
        'Imatra',
        'Lappeenranta',
        'Lemi',
        'Luumäki',
        'Parikkala',
        'Rautjärvi',
        'Ruokolahti',
        'Savitaipale',
        'Taipalsaari',
        'Ylämaa',
      ],
    },
  },
  {
    id: 3,
    county: {
      name: 'Etelä-Pohjanmaa',
      municipalities: [
        'Isokyrö',
        'Alajärvi',
        'Alavus',
        'Evijärvi',
        'Ilmajoki',
        'Isojoki',
        'Karijoki',
        'Kauhajoki',
        'Kauhava',
        'Kuortane',
        'Kurikka',
        'Lappajärvi',
        'Lapua',
        'Seinäjoki',
        'Soini',
        'Teuva',
        'Vimpeli',
        'Ähtäri',
      ],
    },
  },

  {
    id: 4,
    county: {
      name: 'Etelä-Savo',
      municipalities: [
        'Enonkoski',
        'Hirvensalmi',
        'Juva',
        'Kangasniemi',
        'Mikkeli',
        'Mäntyharju',
        'Pertunmaa',
        'Pieksämäki',
        'Puumala',
        'Rantasalmi',
        'Savonlinna',
        'Sulkava',
        'Ähtäri',
      ],
    },
  },
  {
    id: 5,
    county: {
      name: 'Kainuu',
      municipalities: [
        'Hyrynsalmi',
        'Kajaani',
        'Kuhmo',
        'Paltamo',
        'Puolanka',
        'Ristijärvi',
        'Sotkamo',
        'Suomussalmi',
      ],
    },
  },
  {
    id: 6,
    county: {
      name: 'Kanta-Häme',
      municipalities: [
        'Forssa',
        'Hattula',
        'Hausjärvi',
        'Humppila',
        'Hämeenlinna',
        'Janakkala',
        'Jokioinen',
        'Loppi',
        'Riihimäki',
        'Tammela',
        'Ypäjä',
      ],
    },
  },
  {
    id: 7,
    county: {
      name: 'Keski-Pohjanmaa',
      municipalities: [
        'Halsua',
        'Kannus',
        'Kaustinen',
        'Kokkola',
        'Lestijärvi',
        'Perho',
        'Toholampi',
        'Veteli',
      ],
    },
  },
  {
    id: 8,
    county: {
      name: 'Keski-Suomi',
      municipalities: [
        'Hankasalmi',
        'Joutsua',
        'Jyväskylä',
        'Jämsä',
        'Kannonkoski',
        'Karstula',
        'Kinnula',
        'Kivijärvi',
        'Konnevesi',
        'Kyyjärvi',
        'Laukaa',
        'Multia',
        'Muurame',
        'Petäjävesi',
        'Pihtipudas',
        'Saarijärvi',
        'Toivakka',
        'Uurainen',
        'Viitasaari',
        'Äänekoski',
      ],
    },
  },
  {
    id: 9,
    county: {
      name: 'Kymenlaakso',
      municipalities: [
        'Hamina',
        'Kotka',
        'Kouvola',
        'Miehikkälä',
        'Pyhtää',
        'Virolahti',
      ],
    },
  },
  {
    id: 10,
    county: {
      name: 'Lappi',
      municipalities: [
        'Enontekiö',
        'Inari',
        'Kemi',
        'Kemijärvi',
        'Kittilä',
        'Keminmaa',
        'Kittilä',
        'Kolari',
        'Muonio',
        'Pelkosenniemi',
        'Pello',
        'Posio',
        'Ranua',
        'Rovaniemi',
        'Salla',
        'Savukoski',
        'Simo',
        'Sodankylä',
        'Tervola',
        'Tornio',
        'Utsjoki',
        'Ylitornio',
      ],
    },
  },
  {
    id: 11,
    county: {
      name: 'Pirkanmaa',
      municipalities: [
        'Kuhmoinen',
        'Akaa',
        'Kemi',
        'Hämeenkyrö',
        'Ikaalinen',
        'Juupajoki',
        'Kangasala',
        'Kihniö',
        'Lempäälä',
        'Mänttä-Vilppula',
        'Nokia',
        'Orivesi',
        'Parkano',
        'Pirkkala',
        'Punkalaidun',
        'Pälkäne',
        'Ruovesi',
        'Sastamala',
        'Tampere',
        'Urjala',
        'Valkeakoski',
        'Vesilahti',
        'Virrat',
        'Ylöjärvi',
      ],
    },
  },
  {
    id: 12,
    county: {
      name: 'Pohjanmaa',
      municipalities: [
        'Kaskinen',
        'Körsnäs',
        'Kristiinankaupunki',
        'Kruunupyy',
        'Laihia',
        'Luoto',
        'Maalahti',
        'Mustasaari',
        'Närpiö',
        'Pedersören kunta',
        'Pietarsaari',
        'Uusikaarlepyy',
        'Vaasa',
        'Vöyri',
      ],
    },
  },
  {
    id: 13,
    county: {
      name: 'Pohjois-Karjala',
      municipalities: [
        'Ilomantsi',
        'Joensuu',
        'Juuka',
        'Kitee',
        'Kontiolahti',
        'Lieksa',
        'Liperi',
        'Nurmes',
        'Outokumpu',
        'Polvijärvi',
        'Rääkkylä',
        'Tohmajärvi',
        'Heinävesi',
      ],
    },
  },
  {
    id: 14,
    county: {
      name: 'Pohjois-Pohjanmaa',
      municipalities: [
        'Alavieska',
        'Haapajärvi',
        'Haapavesi',
        'Hailuoto',
        'Ii',
        'Kalajoki',
        'Kempele',
        'Kuusamo',
        'Kärsämäki',
        'Liminka',
        'Lumijoki',
        'Merijärvi',
        'Muhos',
        'Nivala',
        'Oulainen',
        'Pudasjärvi',
        'Pyhäjoki',
        'Pyhäjärvi',
        'Pyhäntä',
        'Raahe',
        'Reisjärvi',
        'Sievi',
        'Siikajoki',
        'Siikalatva',
        'Taivalkoski',
        'Tyrnävä',
        'Utajärvi',
        'Ylivieska',
        'Vaala',
      ],
    },
  },
  {
    id: 15,
    county: {
      name: 'Pohjois-Savo',
      municipalities: [
        'Iisalmi',
        'Kaavi',
        'Keitele',
        'Kiuruvesi',
        'Kuopio',
        'Lapinlahti',
        'Leppävirta',
        'Pielavesi',
        'Rautalampi',
        'Rautavaara',
        'Siilinjärvi',
        'Sonkajärvi',
        'Suonenjoki',
        'Tervo',
        'Tuusniemi',
        'Varkaus',
        'Vesanto',
        'Vieremä',
        'Joroinen',
      ],
    },
  },
  {
    id: 16,
    county: {
      name: 'Päijät-Häme',
      municipalities: [
        'Asikkala',
        'Hartola',
        'Heinola',
        'Hollola',
        'Kärkölä',
        'Lahti',
        'Orimattila',
        'Padasjoki',
        'Sysmä',
        'Iitti',
      ],
    },
  },
  {
    id: 17,
    county: {
      name: 'Satakunta',
      municipalities: [
        'Eura',
        'Eurajoki',
        'Harjavalta',
        'Huittinen',
        'Jämijärvi',
        'Kankaanpää',
        'Karvia',
        'Kokemäki',
        'Merikarvia',
        'Nakkila',
        'Noormarkku',
        'Pomarkku',
        'Pori',
        'Rauma',
        'Siikainen',
        'Säkylä',
        'Ulvila',
      ],
    },
  },
  {
    id: 18,
    county: {
      name: 'Uusimaa',
      municipalities: [
        'Askola',
        'Espoo',
        'Hanko',
        'Helsinki',
        'Hyvinkää',
        'Inkoo',
        'Järvenpää',
        'Karkkila',
        'Kauniainen',
        'Kerava',
        'Kirkkonummi',
        'Lapinjärvi',
        'Liljendal',
        'Lohja',
        'Loviisa',
        'Mäntsälä',
        'Myrskylä',
        'Nurmijärvi',
        'Pernaja',
        'Pornainen',
        'Porvoo',
        'Pukkila',
        'Raasepori',
        'Ruotsinpyhtää',
        'Sipoo',
        'Siuntio',
        'Tuusula',
        'Vantaa',
        'Vihti',
      ],
    },
  },
  {
    id: 19,
    county: {
      name: 'Varsinais-Suomi',
      municipalities: [
        'Aura',
        'Kaarina',
        'Kemiönsaari',
        'Koski Tl',
        'Kustavi',
        'Laitila',
        'Lieto',
        'Loimaa',
        'Parainen',
        'Marttila',
        'Masku',
        'Mynämäki',
        'Naantali',
        'Nousiainen',
        'Oripää',
        'Paimio',
        'Pyhäranta',
        'Pöytyä',
        'Raisio',
        'Rusko',
        'Salo',
        'Sauvo',
        'Somero',
        'Taivassalo',
        'Turku',
        'Uusikaupunki',
        'Vehmaa',
      ],
    },
  },
]

export {counties}
